//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.9.0
//
// Created by Quasar Development at 23-10-2015
//
//---------------------------------------------------


#import <Foundation/Foundation.h>
#import "DDXML.h"
@protocol MWKIReferenceObject
@end
    
@class MWKRequestResultHandler;
typedef void (^MWKCLB)(MWKRequestResultHandler *);

#define SOAPVERSION_10      1
#define SOAPVERSION_11      2
#define SOAPVERSION_12      3

@interface MWKRequestResultHandler : NSObject
{
    NSMutableData* receivedBuffer;
    NSURLConnection* connection;
    NSMutableDictionary* namespaces;
    DDXMLDocument *xml;
    NSURLResponse* responseObj;
    int soapVersion;
    NSString* envNS;
}
@property BOOL EnableLogging;
@property (retain, nonatomic) DDXMLElement* Body;
@property (retain, nonatomic) DDXMLElement* Header;    
@property (retain, nonatomic) DDXMLElement* OutputHeader;
@property (retain, nonatomic) DDXMLElement* OutputBody;
@property (retain, nonatomic) NSError* OutputFault;
@property (nonatomic,copy) MWKCLB Callback;

-(id) init;
-(id)init:(int) version;
-(id)createObject: (DDXMLElement*) node type:(Class) type;
-(NSString*) getEnvelopeString;
-(DDXMLDocument*) createEnvelopeXml;
-(id) createInstance:(Class) type node: (DDXMLNode*)node request :(MWKRequestResultHandler *)request;
-(DDXMLElement*) writeElement:(NSString*)name URI: (NSString*) URI parent:(DDXMLElement*) parent;
-(DDXMLElement*) writeElement:(id)obj type:(Class)type name: (NSString*)name URI: (NSString*) URI parent:(DDXMLElement*) parent skipNullProperty:(BOOL)skipNullProperty;
-(DDXMLNode*) addAttribute:(NSString*) name URI:(NSString*) URI stringValue:(NSString*) stringValue element:(DDXMLElement*) element;
-(void)setResponse:(NSData *)responseData response:(NSURLResponse*) response;
-(void) sendImplementation:(NSMutableURLRequest*) request callbackDelegate:(MWKCLB) callbackDelegate;
-(void)Cancel;    

-(void) sendImplementation:(NSMutableURLRequest*) request;

-(void) prepareRequest:(NSMutableURLRequest*)request;
@end

@protocol MWKISerializableObject
-(void) serialize:(DDXMLElement*)__parent __request:(MWKRequestResultHandler*) __request;
@end