//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.9.0
//
// Created by Quasar Development at 23-10-2015
//
//---------------------------------------------------



#import <Foundation/Foundation.h>

#import "DDXML.h"

@class MWKRequestResultHandler;

@protocol MWKSoapServiceResponse < NSObject>
- (void) onSuccess: (id) value methodName:(NSString*)methodName;
- (void) onError: (NSError*) error;
@end


@interface MWKwsDemostracionBinding : NSObject
    
@property (retain, nonatomic) NSDictionary* Headers;
@property (retain, nonatomic) NSString* Url;
@property (nonatomic) BOOL ShouldAddAdornments;
@property BOOL EnableLogging;

- (id) init;
- (id) initWithUrl: (NSString*) url;

-(NSMutableURLRequest*) createLoginUsuarioRequest:(NSString*) Usuario Password:(NSString*) Password __request:(MWKRequestResultHandler*) __request;
-(NSString*) LoginUsuario:(NSString*) Usuario Password:(NSString*) Password __error:(NSError**) __error;
-(MWKRequestResultHandler*) LoginUsuarioAsync:(NSString*) Usuario Password:(NSString*) Password __target:(id) __target __handler:(SEL) __handler;
-(MWKRequestResultHandler*) LoginUsuarioAsync:(NSString*) Usuario Password:(NSString*) Password __target:(id<MWKSoapServiceResponse>) __target;
-(MWKRequestResultHandler*) LoginUsuarioAsyncWithBlock:(NSString*) Usuario Password:(NSString*) Password __handler:(void(^) (id)) __handler;
-(NSMutableURLRequest*) createRegistraImagenRequest:(NSString*) ApiKey UUID:(NSString*) UUID Codigo:(NSString*) Codigo ImgBase64:(NSString*) ImgBase64 __request:(MWKRequestResultHandler*) __request;
-(NSString*) RegistraImagen:(NSString*) ApiKey UUID:(NSString*) UUID Codigo:(NSString*) Codigo ImgBase64:(NSString*) ImgBase64 __error:(NSError**) __error;
-(MWKRequestResultHandler*) RegistraImagenAsync:(NSString*) ApiKey UUID:(NSString*) UUID Codigo:(NSString*) Codigo ImgBase64:(NSString*) ImgBase64 __target:(id) __target __handler:(SEL) __handler;
-(MWKRequestResultHandler*) RegistraImagenAsync:(NSString*) ApiKey UUID:(NSString*) UUID Codigo:(NSString*) Codigo ImgBase64:(NSString*) ImgBase64 __target:(id<MWKSoapServiceResponse>) __target;
-(MWKRequestResultHandler*) RegistraImagenAsyncWithBlock:(NSString*) ApiKey UUID:(NSString*) UUID Codigo:(NSString*) Codigo ImgBase64:(NSString*) ImgBase64 __handler:(void(^) (id)) __handler;
-(NSString*) LoginUsuario2:(NSString*) Usuario Password:(NSString*) Password ApiKey:(NSString*) ApiKey __error:(NSError**) __error;
-(MWKRequestResultHandler*) LoginUsuario2Async:(NSString*) Usuario Password:(NSString*) Password ApiKey:(NSString*) ApiKey __target:(id) __target __handler:(SEL) __handler;
-(MWKRequestResultHandler*) LoginUsuario2Async:(NSString*) Usuario Password:(NSString*) Password ApiKey:(NSString*) ApiKey __target:(id<MWKSoapServiceResponse>) __target;
-(MWKRequestResultHandler*) LoginUsuario2AsyncWithBlock:(NSString*) Usuario Password:(NSString*) Password ApiKey:(NSString*) ApiKey __handler:(void(^) (id)) __handler;
-(MWKRequestResultHandler*) CreateRequestResultHandler;   
-(NSMutableURLRequest*) createRequest :(NSString*) soapAction __request:(MWKRequestResultHandler*) __request; 
-(void) sendImplementation:(NSMutableURLRequest*) request requestMgr:(MWKRequestResultHandler*) requestMgr; 
-(void) sendImplementation:(NSMutableURLRequest*) request requestMgr:(MWKRequestResultHandler*) requestMgr callback:(void (^)(MWKRequestResultHandler *)) callback;

@end
