//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.9.0
//
// Created by Quasar Development at 23-10-2015
//
//---------------------------------------------------


#import "MWKwsDemostracionBinding.h"
#import "MWKRequestResultHandler.h"
#import "MWKHelper.h"

@implementation MWKwsDemostracionBinding
@synthesize Url,ShouldAddAdornments,Headers;
@synthesize EnableLogging;

- (id) init {
    if(self = [super init])
    {
        self.Url=@"http://74.50.116.91:4545/SOAP?service=wsDemostracion";
        self.ShouldAddAdornments=YES;
    }
    return self;
}

- (id) initWithUrl: (NSString*) url {
    if(self = [self init])
    {
        self.Url=url;
    }
    return self;
}

-(void) sendImplementation:(NSMutableURLRequest*) request requestMgr:(MWKRequestResultHandler*) requestMgr
{
    [requestMgr sendImplementation:request];
}

-(MWKRequestResultHandler*) CreateRequestResultHandler
{
    MWKRequestResultHandler* handler= [[MWKRequestResultHandler alloc]init:SOAPVERSION_11];
    handler.EnableLogging = EnableLogging;
    return handler;
}

-(NSMutableURLRequest*) createRequest:(NSString *)__soapAction __request:(MWKRequestResultHandler*) __request
{
    NSURL *__url = [NSURL URLWithString:Url];
    NSMutableURLRequest *__requestObj = [NSMutableURLRequest requestWithURL:__url];
    [__request prepareRequest:__requestObj];

    [__requestObj addValue: [NSString stringWithFormat:@"\"%@\"", __soapAction] forHTTPHeaderField:@"SOAPAction"];

    for (NSString* key in self.Headers) {
        [__requestObj addValue: [self.Headers objectForKey:key] forHTTPHeaderField:key];
    }
    [__requestObj setHTTPMethod:@"POST"];

    return __requestObj;
}


-(void) sendImplementation:(NSMutableURLRequest*) request requestMgr:(MWKRequestResultHandler*) requestMgr callback:(void (^)(MWKRequestResultHandler *)) callback
{
    [requestMgr sendImplementation:request callbackDelegate:callback];
}

-(void) addAdornments:(DDXMLElement*)__methodElement
{
    if(ShouldAddAdornments)
    {
        [__methodElement addAttribute:[DDXMLNode attributeWithName:@"id" stringValue:@"o0"]];
        [__methodElement addAttribute:[DDXMLNode attributeWithName:@"c:root" stringValue:@"1"]];
    }
}

-(NSMutableURLRequest*) createLoginUsuarioRequest:(NSString*) Usuario Password:(NSString*) Password __request:(MWKRequestResultHandler*) __request
{
    DDXMLElement *__methodElement=[__request writeElement:@"wsDemostracion___LoginUsuario" URI:@"urn:ws.prueba" parent:__request.Body];
    [self addAdornments:__methodElement];
            
    DDXMLElement* __UsuarioItemElement=[__request writeElement:Usuario type:[NSString class] name:@"Usuario" URI:@"urn:ws.prueba" parent:__methodElement skipNullProperty:NO];
    if(__UsuarioItemElement!=nil)
    {
        [__UsuarioItemElement setStringValue:Usuario];
    }
            
    DDXMLElement* __PasswordItemElement=[__request writeElement:Password type:[NSString class] name:@"Password" URI:@"urn:ws.prueba" parent:__methodElement skipNullProperty:NO];
    if(__PasswordItemElement!=nil)
    {
        [__PasswordItemElement setStringValue:Password];
    }
    
    NSMutableURLRequest* __requestObj= [self createRequest:@"urn:LibraryCandidatos-wsDemostracion#LoginUsuario"  __request:__request];
    return __requestObj;
    }
    
-(MWKRequestResultHandler*) LoginUsuarioAsync:(NSString*) Usuario Password:(NSString*) Password __target:(id) __target __handler:(SEL) __handler
{
    MWKRequestResultHandler* __request = [self CreateRequestResultHandler];
    NSMutableURLRequest *__requestObj=[self createLoginUsuarioRequest:Usuario Password: Password __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request callback:^(MWKRequestResultHandler *__requestMgr) {
    id __res;
    if(__requestMgr.OutputFault==nil)
    {
        DDXMLElement *__result=[MWKHelper getResultElement:__request.OutputBody name:@"Result"];
        __res= [__result stringValue];
    }
    else
    {
        __res=__requestMgr.OutputFault;
    }
    
    IMP imp = [__target methodForSelector:__handler];
    void (*func)(id, SEL,id) = (void *)imp;
    func(__target, __handler,__res);
    }];
    return __request;
}

-(MWKRequestResultHandler*) LoginUsuarioAsync:(NSString*) Usuario Password:(NSString*) Password __target:(id<MWKSoapServiceResponse>) __target
{
    MWKRequestResultHandler* __request = [self CreateRequestResultHandler];
    NSMutableURLRequest *__requestObj=[self createLoginUsuarioRequest:Usuario Password: Password __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request callback:^(MWKRequestResultHandler *__requestMgr) {
    if(__requestMgr.OutputFault==nil)
    {
        DDXMLElement *__result=[MWKHelper getResultElement:__request.OutputBody name:@"Result"];
        [__target onSuccess:[__result stringValue] methodName:@"LoginUsuario"];
    }
    else
    {
        [__target onError:__requestMgr.OutputFault];
    }
    }];
    return __request;
}
-(MWKRequestResultHandler*) LoginUsuarioAsyncWithBlock:(NSString*) Usuario Password:(NSString*) Password __handler:(void(^) (id)) __handler
{
    MWKRequestResultHandler* __request = [self CreateRequestResultHandler];
    NSMutableURLRequest *__requestObj=[self createLoginUsuarioRequest:Usuario Password: Password __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request callback:^(MWKRequestResultHandler *__requestMgr) {
    id __res;
    if(__requestMgr.OutputFault==nil)
    {
        DDXMLElement *__result=[MWKHelper getResultElement:__request.OutputBody name:@"Result"];
        __res= [__result stringValue];
    }
    else
    {
    __res=__requestMgr.OutputFault;
    }
    
    __handler(__res);
    }];
    return __request;
    }

-(NSString*) LoginUsuario:(NSString*) Usuario Password:(NSString*) Password __error:(NSError**) __error
{
    MWKRequestResultHandler* __request = [self CreateRequestResultHandler];
    NSMutableURLRequest *__requestObj=[self createLoginUsuarioRequest:Usuario Password: Password __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request ];
    if(__request.OutputFault!=nil)
    {
        if(__error)
        {
            *__error=__request.OutputFault;
        }
        return nil;
    }
    DDXMLElement *__result=[MWKHelper getResultElement:__request.OutputBody name:@"Result"];
    return [__result stringValue];
}
-(NSMutableURLRequest*) createRegistraImagenRequest:(NSString*) ApiKey UUID:(NSString*) UUID Codigo:(NSString*) Codigo ImgBase64:(NSString*) ImgBase64 __request:(MWKRequestResultHandler*) __request
{
    DDXMLElement *__methodElement=[__request writeElement:@"wsDemostracion___RegistraImagen" URI:@"urn:ws.prueba" parent:__request.Body];
    [self addAdornments:__methodElement];
            
    DDXMLElement* __ApiKeyItemElement=[__request writeElement:ApiKey type:[NSString class] name:@"ApiKey" URI:@"urn:ws.prueba" parent:__methodElement skipNullProperty:NO];
    if(__ApiKeyItemElement!=nil)
    {
        [__ApiKeyItemElement setStringValue:ApiKey];
    }
            
    DDXMLElement* __UUIDItemElement=[__request writeElement:UUID type:[NSString class] name:@"UUID" URI:@"urn:ws.prueba" parent:__methodElement skipNullProperty:NO];
    if(__UUIDItemElement!=nil)
    {
        [__UUIDItemElement setStringValue:UUID];
    }
            
    DDXMLElement* __CodigoItemElement=[__request writeElement:Codigo type:[NSString class] name:@"Codigo" URI:@"urn:ws.prueba" parent:__methodElement skipNullProperty:NO];
    if(__CodigoItemElement!=nil)
    {
        [__CodigoItemElement setStringValue:Codigo];
    }
            
    DDXMLElement* __ImgBase64ItemElement=[__request writeElement:ImgBase64 type:[NSString class] name:@"ImgBase64" URI:@"urn:ws.prueba" parent:__methodElement skipNullProperty:NO];
    if(__ImgBase64ItemElement!=nil)
    {
        [__ImgBase64ItemElement setStringValue:ImgBase64];
    }
    
    NSMutableURLRequest* __requestObj= [self createRequest:@"urn:LibraryCandidatos-wsDemostracion#RegistraImagen"  __request:__request];
    return __requestObj;
    }
    
-(MWKRequestResultHandler*) RegistraImagenAsync:(NSString*) ApiKey UUID:(NSString*) UUID Codigo:(NSString*) Codigo ImgBase64:(NSString*) ImgBase64 __target:(id) __target __handler:(SEL) __handler
{
    MWKRequestResultHandler* __request = [self CreateRequestResultHandler];
    NSMutableURLRequest *__requestObj=[self createRegistraImagenRequest:ApiKey UUID: UUID Codigo: Codigo ImgBase64: ImgBase64 __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request callback:^(MWKRequestResultHandler *__requestMgr) {
    id __res;
    if(__requestMgr.OutputFault==nil)
    {
        DDXMLElement *__result=[MWKHelper getResultElement:__request.OutputBody name:@"Result"];
        __res= [__result stringValue];
    }
    else
    {
        __res=__requestMgr.OutputFault;
    }
    
    IMP imp = [__target methodForSelector:__handler];
    void (*func)(id, SEL,id) = (void *)imp;
    func(__target, __handler,__res);
    }];
    return __request;
}

-(MWKRequestResultHandler*) RegistraImagenAsync:(NSString*) ApiKey UUID:(NSString*) UUID Codigo:(NSString*) Codigo ImgBase64:(NSString*) ImgBase64 __target:(id<MWKSoapServiceResponse>) __target
{
    MWKRequestResultHandler* __request = [self CreateRequestResultHandler];
    NSMutableURLRequest *__requestObj=[self createRegistraImagenRequest:ApiKey UUID: UUID Codigo: Codigo ImgBase64: ImgBase64 __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request callback:^(MWKRequestResultHandler *__requestMgr) {
    if(__requestMgr.OutputFault==nil)
    {
        DDXMLElement *__result=[MWKHelper getResultElement:__request.OutputBody name:@"Result"];
        [__target onSuccess:[__result stringValue] methodName:@"RegistraImagen"];
    }
    else
    {
        [__target onError:__requestMgr.OutputFault];
    }
    }];
    return __request;
}
-(MWKRequestResultHandler*) RegistraImagenAsyncWithBlock:(NSString*) ApiKey UUID:(NSString*) UUID Codigo:(NSString*) Codigo ImgBase64:(NSString*) ImgBase64 __handler:(void(^) (id)) __handler
{
    MWKRequestResultHandler* __request = [self CreateRequestResultHandler];
    NSMutableURLRequest *__requestObj=[self createRegistraImagenRequest:ApiKey UUID: UUID Codigo: Codigo ImgBase64: ImgBase64 __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request callback:^(MWKRequestResultHandler *__requestMgr) {
    id __res;
    if(__requestMgr.OutputFault==nil)
    {
        DDXMLElement *__result=[MWKHelper getResultElement:__request.OutputBody name:@"Result"];
        __res= [__result stringValue];
    }
    else
    {
    __res=__requestMgr.OutputFault;
    }
    
    __handler(__res);
    }];
    return __request;
    }

-(NSString*) RegistraImagen:(NSString*) ApiKey UUID:(NSString*) UUID Codigo:(NSString*) Codigo ImgBase64:(NSString*) ImgBase64 __error:(NSError**) __error
{
    MWKRequestResultHandler* __request = [self CreateRequestResultHandler];
    NSMutableURLRequest *__requestObj=[self createRegistraImagenRequest:ApiKey UUID: UUID Codigo: Codigo ImgBase64: ImgBase64 __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request ];
    if(__request.OutputFault!=nil)
    {
        if(__error)
        {
            *__error=__request.OutputFault;
        }
        return nil;
    }
    DDXMLElement *__result=[MWKHelper getResultElement:__request.OutputBody name:@"Result"];
    return [__result stringValue];
}
    
-(MWKRequestResultHandler*) LoginUsuario2Async:(NSString*) Usuario Password:(NSString*) Password ApiKey:(NSString*) ApiKey __target:(id) __target __handler:(SEL) __handler
{
    /*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
    return nil;
}

-(MWKRequestResultHandler*) LoginUsuario2Async:(NSString*) Usuario Password:(NSString*) Password ApiKey:(NSString*) ApiKey __target:(id<MWKSoapServiceResponse>) __target
{
    /*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
    return nil;
}
-(MWKRequestResultHandler*) LoginUsuario2AsyncWithBlock:(NSString*) Usuario Password:(NSString*) Password ApiKey:(NSString*) ApiKey __handler:(void(^) (id)) __handler
{
    /*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
    return nil;
    }

-(NSString*) LoginUsuario2:(NSString*) Usuario Password:(NSString*) Password ApiKey:(NSString*) ApiKey __error:(NSError**) __error
{
    /*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
    return nil;
}

@end
